package es.jklabs;/*
 * es.jklabs.Acercade.java
 *
 * Created on 17 de septiembre de 2005, 12:44
 */

/**
 * @author Juanky
 */
public class Acercade extends javax.swing.JDialog {

    /**
     * Creates new form es.jklabs.Acercade
     */
    public Acercade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JTextArea info = new javax.swing.JTextArea();
        javax.swing.JToggleButton aceptar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de...");
        setName("es.jklabs.Acercade");
        info.setBackground(java.awt.Color.lightGray);
        info.setEditable(false);
        info.setText("M.C.D. Java V.1.0\n\nEste programa busca el maximo comun divisor \nde 2 n\u00ba enteros.\n\nRealizado por Juan Carlos Prieto Silos.\n\nContacto: oneclick18@gmail.com\n\nAutorizada su libre distribucion.");
        getContentPane().add(info, java.awt.BorderLayout.CENTER);

        aceptar.setText("Ok");
        aceptar.addActionListener(evt -> aceptarActionPerformed());

        getContentPane().add(aceptar, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void aceptarActionPerformed() {//GEN-FIRST:event_aceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_aceptarActionPerformed
    // End of variables declaration//GEN-END:variables

}
