package es.jklabs;/*
 * es.jklabs.Principal.java
 *
 * Created on 8 de septiembre de 2005, 13:41
 */

import es.jklabs.gui.dialgos.Acercade;
import es.jklabs.gui.utilidades.Growls;
import es.jklabs.utilidades.Logger;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/**
 * @author Juanky
 */
public class Principal extends javax.swing.JFrame {

    private javax.swing.JButton nuevo;
    private java.awt.TextField resultado;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;

    /**
     * Creates new form es.jklabs.Principal
     */
    private Principal() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Logger.eliminarLogsVacios();
        Logger.init();
        try {
            Growls.init();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                UnsupportedLookAndFeelException e) {
            Logger.error("Cargar el LookAndFeel del S.O", e);
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel x = new javax.swing.JLabel();
        javax.swing.JLabel y = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        javax.swing.JButton run = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        resultado = new java.awt.TextField();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu menu = new javax.swing.JMenu();
        javax.swing.JMenuItem salir = new javax.swing.JMenuItem();
        javax.swing.JMenu ayuda = new javax.swing.JMenu();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JMenuItem acerca = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M.C.D.");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x.setText("X");
        jPanel3.add(x);

        y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        y.setText("Y");
        jPanel3.add(y);

        a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(a);

        b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(b);

        jPanel1.add(jPanel3);

        run.setIcon(new javax.swing.ImageIcon("C:\\!conMania Collection\\Science\\Calculator.JPG"));
        run.setMnemonic('C');
        run.setText("Calcular");
        run.addActionListener(evt -> RunActionPerformed());

        jPanel1.add(run);

        nuevo.setMnemonic('N');
        nuevo.setText("nuevo M.C.D.");
        nuevo.setEnabled(false);
        nuevo.addActionListener(evt -> NuevoActionPerformed());

        jPanel1.add(nuevo);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(new javax.swing.border.TitledBorder("resultado"));
        resultado.setEditable(false);
        resultado.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 12));
        jPanel2.add(resultado);

        getContentPane().add(jPanel2);

        menu.setMnemonic('M');
        menu.setText("Menu");
        salir.setText("Salir");
        salir.addActionListener(evt -> SalirActionPerformed());

        menu.add(salir);

        jMenuBar1.add(menu);

        ayuda.setMnemonic('A');
        ayuda.setText("Ayuda");
        acerca.setText("Acerca de...");
        acerca.addActionListener(evt -> AcercaActionPerformed());

        ayuda.add(acerca);

        jMenuBar1.add(ayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void NuevoActionPerformed() {//GEN-FIRST:event_NuevoActionPerformed
        if (!Objects.equals(resultado.getText(), "Error")) {
            a.setText(resultado.getText());
            b.setText("");
            nuevo.setEnabled(false);
        }
    }//GEN-LAST:event_NuevoActionPerformed

    private void AcercaActionPerformed() {//GEN-FIRST:event_AcercaActionPerformed
        Acercade acerca1 = new Acercade(new javax.swing.JFrame(), true);
        acerca1.setVisible(true);
    }//GEN-LAST:event_AcercaActionPerformed

    private void SalirActionPerformed() {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void RunActionPerformed() {//GEN-FIRST:event_RunActionPerformed
        try {
            int x;
            int y;
            int c;
            int r;
            String aux = a.getText();
            x = Integer.parseInt(aux);
            aux = b.getText();
            y = Integer.parseInt(aux);
            if (y > x) {
                int z;
                z = x;
                x = y;
                y = z;
            }
            c = x / y;
            r = x - c * y;
            while (r != 0) {
                x = y;
                y = r;
                c = x / y;
                r = x - c * y;
            }
            resultado.setText(String.valueOf(y));
            nuevo.setEnabled(true);
        } catch (java.lang.NumberFormatException e) {
            resultado.setText("Error");
            nuevo.setEnabled(false);
        }
    }//GEN-LAST:event_RunActionPerformed
    // End of variables declaration//GEN-END:variables

}
