/*
 * Acercade.java
 *
 * Created on 17 de septiembre de 2005, 12:44
 */

/**
 * @author Juanky
 */
public class Acercade extends javax.swing.JDialog {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Info;
    private javax.swing.JToggleButton aceptar;

    /**
     * Creates new form Acercade
     */
    public Acercade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        Info = new javax.swing.JTextArea();
        aceptar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de...");
        setName("Acercade");
        Info.setBackground(java.awt.Color.lightGray);
        Info.setEditable(false);
        Info.setText("M.C.D. Java V.1.0\n\nEste programa busca el maximo comun divisor \nde 2 n\u00ba enteros.\n\nRealizado por Juan Carlos Prieto Silos.\n\nContacto: oneclick18@gmail.com\n\nAutorizada su libre distribucion.");
        getContentPane().add(Info, java.awt.BorderLayout.CENTER);

        aceptar.setText("Ok");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        getContentPane().add(aceptar, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_aceptarActionPerformed
    // End of variables declaration//GEN-END:variables

}
