/*
 * Principal.java
 *
 * Created on 8 de septiembre de 2005, 13:41
 */

/**
 * @author Juanky
 */
public class Principal extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Acerca;
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenu Menu;
    private javax.swing.JButton Nuevo;
    private java.awt.TextField Resultado;
    private javax.swing.JButton Run;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel x;
    private javax.swing.JLabel y;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        y = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        Run = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Resultado = new java.awt.TextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        Acerca = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("M.C.D.");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x.setText("X");
        jPanel3.add(x);

        y.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        y.setText("Y");
        jPanel3.add(y);

        a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(a);

        b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(b);

        jPanel1.add(jPanel3);

        Run.setIcon(new javax.swing.ImageIcon("C:\\!conMania Collection\\Science\\Calculator.JPG"));
        Run.setMnemonic('C');
        Run.setText("Calcular");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });

        jPanel1.add(Run);

        Nuevo.setMnemonic('N');
        Nuevo.setText("Nuevo M.C.D.");
        Nuevo.setEnabled(false);
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        jPanel1.add(Nuevo);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Resultado"));
        Resultado.setEditable(false);
        Resultado.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jPanel2.add(Resultado);

        getContentPane().add(jPanel2);

        Menu.setMnemonic('M');
        Menu.setText("Menu");
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Menu.add(Salir);

        jMenuBar1.add(Menu);

        Ayuda.setMnemonic('A');
        Ayuda.setText("Ayuda");
        Acerca.setText("Acerca de...");
        Acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaActionPerformed(evt);
            }
        });

        Ayuda.add(Acerca);

        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        // TODO add your handling code here:
        if (Resultado.getText() != "Error") {
            a.setText(Resultado.getText());
            b.setText("");
            Nuevo.setEnabled(false);
        }
    }//GEN-LAST:event_NuevoActionPerformed

    private void AcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaActionPerformed
        // TODO add your handling code here:
        Acercade acerca1 = new Acercade(new javax.swing.JFrame(), true);
        acerca1.setVisible(true);
    }//GEN-LAST:event_AcercaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
        try {
            int x;
            int y;
            int c;
            int r;
            String aux = a.getText();
            x = Integer.parseInt(aux);
            aux = b.getText();
            y = Integer.parseInt(aux);
            if (y > x) {
                int z;
                z = x;
                x = y;
                y = z;
            }
            c = x / y;
            r = x - c * y;
            while (r != 0) {
                x = y;
                y = r;
                c = x / y;
                r = x - c * y;
            }
            Resultado.setText(String.valueOf(y));
            Nuevo.setEnabled(true);
        } catch (java.lang.NumberFormatException e) {
            Resultado.setText("Error");
            Nuevo.setEnabled(false);
        }
    }//GEN-LAST:event_RunActionPerformed
    // End of variables declaration//GEN-END:variables

}
